name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn clean
        mvn test
        mvn install

    - name: Deploy WAR to Tomcat
      env:
        TOMCAT_URL: http://18.206.223.14:8081/manager/text
        TOMCAT_USER: admin
        TOMCAT_PASS: admin
      run: |
        WAR_PATH=$(find target -name '*.war' | head -n 1)
        echo "Deploying WAR: $WAR_PATH"

        # Deploy WAR via Tomcat manager text interface
        curl --upload-file "$WAR_PATH" \
          --user "$TOMCAT_USER:$TOMCAT_PASS" \
          "$TOMCAT_URL/deploy?path=/&update=true"
